### PR TITLE
Quality check testrun

### PR DESCRIPTION
**Pull request by StefanVriend**
This PR involves:

- [x] - Add new check C5: checking that the age of subsequent captures is in the correct order (#157)
- [x] - Add check descriptions to the quality check report (#158)
- [x] - Add reference values to quality check report (#158)
- [ ] - Change save path of quality check function (#159)

### CODE REVIEW

**Comment by StefanVriend** [comment]
All tests in `devtools::test()` passed.
@LiamDBailey Shall we look at the save path (#159) before reviewing this PR & merging into the master?

**Comment by LiamDBailey** [comment]
@StefanVriend let's leave that for later. Shouldn't affect output given to the data owner so we can do that later, maybe when we talk about infrastructure. I'll check the tests are also running on my side and then we can merge.

**Comment by LiamDBailey** [comment]
Spotted a few small issues that had to be corrected:
- Included documentation for the new B13/14 tests (and removed reference to check_sex_parents) 📜 
- Be careful when copying text from outside of R because you can introduce non-ASCII characters (which R can't deal with). The most common problem is with quotation marks where these slanted quotes are non-ASCII: ‘’ but these straight ones are fine: ''. There were a few cases of this in the new quality check documentation that I spotted 🕵️.

Running `devtools::check()` as well as `devtools::test()` will help to spot these type of things.

**Comment by StefanVriend** [comment]
Thanks, @LiamDBailey!

In my case, `devtools::test()` did not highlight them, but `devtools::check()` did indeed (which I forgot to run before I mailed you).

**Pull request merged**
